import data from './book.json';

/**
 * The Raven, as a pack.
 *
 * `book.json` is the poem: the stanzas, the glossary, the questions, the
 * two of them talking about each part. It is generated from
 * `build/the-raven.html` and there is nothing in it about files.
 *
 * This file is the rest of the pack — where the art and the recordings
 * sit once `tools/extract-media.mjs` has run.
 *
 * WHY THE PICTURE PATHS ARE HERE AND NOT IN book.json
 *
 * Magi keeps its plate map in its book.json, and that is right for Magi:
 * its art is content-addressed, so `art/3ded1a00f03753bd.webp` cannot be
 * derived from the scene id. Lose that map and there is no way back from
 * a scene to its picture. The map carries information, so it is data.
 *
 * The Raven's art is not content-addressed. Every file is named for the
 * key the build used, so `s9` -> `art/plate-s9.webp` is not a fact about
 * the poem, it is the naming scheme one tool chose. That makes it
 * deployment, and deployment belongs in the pack, next to the audio
 * paths, in the file a person edits when the layout changes.
 *
 * The other half of the reason is mechanical. `book/book.json` is
 * generated by the engine's extractor, and this repository already has a
 * scar from editing generated output: `tools/fix-glossary.mjs` exists
 * because a hand-typed correction was silently undone by the next
 * extraction. Paths written into a generated file would go the same way.
 *
 * Relative, with no leading slash — see MEDIA_BASE in reader/beats.js.
 * itch serves a game from a nested path, so "/art/plate-s9.webp"
 * resolves against the domain root and 404s for every picture.
 */

/** The scene plates: cover, the author page, twelve segments, the note
 *  on the poem's afterlife. Keyed by `unit.scene || unit.id`, which is
 *  what beatsOf looks up. */
const plates = {
  cover: 'art/plate-cover.webp',
  poe: 'art/plate-poe.webp',
  s1: 'art/plate-s1.webp',
  s2: 'art/plate-s2.webp',
  s3: 'art/plate-s3.webp',
  s4: 'art/plate-s4.webp',
  s5: 'art/plate-s5.webp',
  s6: 'art/plate-s6.webp',
  s7: 'art/plate-s7.webp',
  s8: 'art/plate-s8.webp',
  s9: 'art/plate-s9.webp',
  s10: 'art/plate-s10.webp',
  s11: 'art/plate-s11.webp',
  s12: 'art/plate-s12.webp',
  impact: 'art/plate-impact.webp',
};

/** The two portraits, put back on the cast members the extractor built.
 *  Speaker.jsx uses `member.art` as an <img src> directly. */
const portraits = {
  wren: 'art/cast-wren.webp',
  prof: 'art/cast-prof.webp',
};

const cast = {
  ...data.cast,
  members: Object.fromEntries(
    Object.entries(data.cast?.members || {}).map(([id, member]) => [
      id,
      portraits[id] ? { ...member, art: portraits[id] } : member,
    ])
  ),
};

/** @type {import('../../lib/types.js').Book} */
export default {
  ...data,
  plates,
  cast,
  media: {
    audio: 'raven-audio/',
    /* Named, not written. There are no recordings for this book and so
       no cues; see AUDIO-NEEDED.md, which says exactly what would have
       to exist. The engine treats a cue file that does not load as "no
       highlighting" and still shows every line, so this is a promise
       about where the file goes, not a claim that it is there. */
    cues: 'cues/raven.vtt',
  },
};

/**
 * The 120 per-line plates are extracted to `art/beat-<unit>-<i>.webp`
 * and are deliberately not mapped here.
 *
 * The build changed the picture on every line of a segment; the engine's
 * `beatsOf` gives every beat in a unit the one plate for that unit.
 * Wiring them up is an engine change, not a pack change, so the files
 * are kept and the map is left for whoever makes it. Two raven sprites
 * (`art/sprite-raven-sit.webp`, `art/sprite-raven-fly.webp`) are in the
 * same position: the build flew a bird across the cue layer, and the
 * engine has no cue layer.
 */
